# Generated by Django 6.0.3 on 2026-04-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='fecha_termino_contrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='tipo_contrato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
