# Generated by Django 6.0.3 on 2026-04-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0003_aviso'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses_minimos', models.IntegerField(default=6)),
                ('dias_iniciales', models.IntegerField(default=10)),
                ('meses_vigencia', models.IntegerField(default=4)),
            ],
            options={
                'verbose_name': 'Configuración de Vacaciones',
                'verbose_name_plural': 'Configuraciones de Vacaciones',
            },
        ),
    ]
